# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: timeseries.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'timeseries.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10timeseries.proto\x12\ntimeseries\"/\n\x0eTimeSeriesData\x12\r\n\x05\x64\x61tes\x18\x01 \x03(\t\x12\x0e\n\x06values\x18\x02 \x03(\x02\"\xbf\x02\n\x11ProphetParameters\x12\x1f\n\x17\x63hangepoint_prior_scale\x18\x01 \x01(\x02\x12\x1f\n\x17seasonality_prior_scale\x18\x02 \x01(\x02\x12\x1c\n\x14holidays_prior_scale\x18\x03 \x01(\x02\x12\x18\n\x10seasonality_mode\x18\x04 \x01(\t\x12\x1a\n\x12yearly_seasonality\x18\x05 \x01(\x08\x12\x1a\n\x12weekly_seasonality\x18\x06 \x01(\x08\x12\x19\n\x11\x64\x61ily_seasonality\x18\x07 \x01(\x08\x12\x0e\n\x06growth\x18\x08 \x01(\t\x12\x0b\n\x03\x63\x61p\x18\t \x01(\x02\x12\r\n\x05\x66loor\x18\n \x01(\x02\x12\x16\n\x0en_changepoints\x18\x0b \x01(\x05\x12\x19\n\x11\x63hangepoint_range\x18\x0c \x01(\x02\"\xa0\x01\n\x0f\x46orecastRequest\x12(\n\x04\x64\x61ta\x18\x01 \x01(\x0b\x32\x1a.timeseries.TimeSeriesData\x12\x0f\n\x07periods\x18\x02 \x01(\x05\x12\x37\n\x10model_parameters\x18\x03 \x01(\x0b\x32\x1d.timeseries.ProphetParameters\x12\x19\n\x11return_components\x18\x04 \x01(\x08\"\x8c\x02\n\x10\x46orecastResponse\x12\x16\n\x0e\x66orecast_dates\x18\x01 \x03(\t\x12\x17\n\x0f\x66orecast_values\x18\x02 \x03(\x02\x12\x1c\n\x14\x66orecast_lower_bound\x18\x03 \x03(\x02\x12\x1c\n\x14\x66orecast_upper_bound\x18\x04 \x03(\x02\x12@\n\ncomponents\x18\x05 \x03(\x0b\x32,.timeseries.ForecastResponse.ComponentsEntry\x1aI\n\x0f\x43omponentsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12%\n\x05value\x18\x02 \x01(\x0b\x32\x16.timeseries.Components:\x02\x38\x01\"\x1c\n\nComponents\x12\x0e\n\x06values\x18\x01 \x03(\x02\"\x07\n\x05\x45mpty2\xa4\x01\n\x11TimeSeriesService\x12\x45\n\x08\x46orecast\x12\x1b.timeseries.ForecastRequest\x1a\x1c.timeseries.ForecastResponse\x12H\n\x14GetDefaultParameters\x12\x11.timeseries.Empty\x1a\x1d.timeseries.ProphetParametersb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'timeseries_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FORECASTRESPONSE_COMPONENTSENTRY']._loaded_options = None
  _globals['_FORECASTRESPONSE_COMPONENTSENTRY']._serialized_options = b'8\001'
  _globals['_TIMESERIESDATA']._serialized_start=32
  _globals['_TIMESERIESDATA']._serialized_end=79
  _globals['_PROPHETPARAMETERS']._serialized_start=82
  _globals['_PROPHETPARAMETERS']._serialized_end=401
  _globals['_FORECASTREQUEST']._serialized_start=404
  _globals['_FORECASTREQUEST']._serialized_end=564
  _globals['_FORECASTRESPONSE']._serialized_start=567
  _globals['_FORECASTRESPONSE']._serialized_end=835
  _globals['_FORECASTRESPONSE_COMPONENTSENTRY']._serialized_start=762
  _globals['_FORECASTRESPONSE_COMPONENTSENTRY']._serialized_end=835
  _globals['_COMPONENTS']._serialized_start=837
  _globals['_COMPONENTS']._serialized_end=865
  _globals['_EMPTY']._serialized_start=867
  _globals['_EMPTY']._serialized_end=874
  _globals['_TIMESERIESSERVICE']._serialized_start=877
  _globals['_TIMESERIESSERVICE']._serialized_end=1041
# @@protoc_insertion_point(module_scope)
