# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import forecast_pb2 as forecast__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in forecast_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ForecastServiceStub(object):
    """The forecasting service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateForecast = channel.unary_unary(
                '/forecast.ForecastService/CreateForecast',
                request_serializer=forecast__pb2.ForecastRequest.SerializeToString,
                response_deserializer=forecast__pb2.ForecastResponse.FromString,
                _registered_method=True)
        self.GetDefaultParameters = channel.unary_unary(
                '/forecast.ForecastService/GetDefaultParameters',
                request_serializer=forecast__pb2.Empty.SerializeToString,
                response_deserializer=forecast__pb2.DefaultParametersResponse.FromString,
                _registered_method=True)


class ForecastServiceServicer(object):
    """The forecasting service definition.
    """

    def CreateForecast(self, request, context):
        """Generates a forecast.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDefaultParameters(self, request, context):
        """Returns the default model parameters as a JSON string.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ForecastServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateForecast': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateForecast,
                    request_deserializer=forecast__pb2.ForecastRequest.FromString,
                    response_serializer=forecast__pb2.ForecastResponse.SerializeToString,
            ),
            'GetDefaultParameters': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDefaultParameters,
                    request_deserializer=forecast__pb2.Empty.FromString,
                    response_serializer=forecast__pb2.DefaultParametersResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'forecast.ForecastService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('forecast.ForecastService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ForecastService(object):
    """The forecasting service definition.
    """

    @staticmethod
    def CreateForecast(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/forecast.ForecastService/CreateForecast',
            forecast__pb2.ForecastRequest.SerializeToString,
            forecast__pb2.ForecastResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDefaultParameters(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/forecast.ForecastService/GetDefaultParameters',
            forecast__pb2.Empty.SerializeToString,
            forecast__pb2.DefaultParametersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
