# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: forecast.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'forecast.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x66orecast.proto\x12\x08\x66orecast\"\x07\n\x05\x45mpty\"/\n\x0eTimeSeriesData\x12\r\n\x05\x64\x61tes\x18\x01 \x03(\t\x12\x0e\n\x06values\x18\x02 \x03(\x02\"\xbf\x02\n\x11ProphetParameters\x12\x1f\n\x17\x63hangepoint_prior_scale\x18\x01 \x01(\x02\x12\x1f\n\x17seasonality_prior_scale\x18\x02 \x01(\x02\x12\x1c\n\x14holidays_prior_scale\x18\x03 \x01(\x02\x12\x18\n\x10seasonality_mode\x18\x04 \x01(\t\x12\x1a\n\x12yearly_seasonality\x18\x05 \x01(\x08\x12\x1a\n\x12weekly_seasonality\x18\x06 \x01(\x08\x12\x19\n\x11\x64\x61ily_seasonality\x18\x07 \x01(\x08\x12\x0e\n\x06growth\x18\x08 \x01(\t\x12\x0b\n\x03\x63\x61p\x18\t \x01(\x02\x12\r\n\x05\x66loor\x18\n \x01(\x02\x12\x16\n\x0en_changepoints\x18\x0b \x01(\x05\x12\x19\n\x11\x63hangepoint_range\x18\x0c \x01(\x02\"\x9c\x01\n\x0f\x46orecastRequest\x12&\n\x04\x64\x61ta\x18\x01 \x01(\x0b\x32\x18.forecast.TimeSeriesData\x12\x0f\n\x07periods\x18\x02 \x01(\x05\x12\x35\n\x10model_parameters\x18\x03 \x01(\x0b\x32\x1b.forecast.ProphetParameters\x12\x19\n\x11return_components\x18\x04 \x01(\x08\"\x1b\n\tFloatList\x12\x0e\n\x06values\x18\x01 \x03(\x02\"\x87\x02\n\x10\x46orecastResponse\x12\x16\n\x0e\x66orecast_dates\x18\x01 \x03(\t\x12\x17\n\x0f\x66orecast_values\x18\x02 \x03(\x02\x12\x1c\n\x14\x66orecast_lower_bound\x18\x03 \x03(\x02\x12\x1c\n\x14\x66orecast_upper_bound\x18\x04 \x03(\x02\x12>\n\ncomponents\x18\x05 \x03(\x0b\x32*.forecast.ForecastResponse.ComponentsEntry\x1a\x46\n\x0f\x43omponentsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\"\n\x05value\x18\x02 \x01(\x0b\x32\x13.forecast.FloatList:\x02\x38\x01\")\n\x19\x44\x65\x66\x61ultParametersResponse\x12\x0c\n\x04json\x18\x01 \x01(\t2\xa8\x01\n\x0f\x46orecastService\x12G\n\x0e\x43reateForecast\x12\x19.forecast.ForecastRequest\x1a\x1a.forecast.ForecastResponse\x12L\n\x14GetDefaultParameters\x12\x0f.forecast.Empty\x1a#.forecast.DefaultParametersResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'forecast_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FORECASTRESPONSE_COMPONENTSENTRY']._loaded_options = None
  _globals['_FORECASTRESPONSE_COMPONENTSENTRY']._serialized_options = b'8\001'
  _globals['_EMPTY']._serialized_start=28
  _globals['_EMPTY']._serialized_end=35
  _globals['_TIMESERIESDATA']._serialized_start=37
  _globals['_TIMESERIESDATA']._serialized_end=84
  _globals['_PROPHETPARAMETERS']._serialized_start=87
  _globals['_PROPHETPARAMETERS']._serialized_end=406
  _globals['_FORECASTREQUEST']._serialized_start=409
  _globals['_FORECASTREQUEST']._serialized_end=565
  _globals['_FLOATLIST']._serialized_start=567
  _globals['_FLOATLIST']._serialized_end=594
  _globals['_FORECASTRESPONSE']._serialized_start=597
  _globals['_FORECASTRESPONSE']._serialized_end=860
  _globals['_FORECASTRESPONSE_COMPONENTSENTRY']._serialized_start=790
  _globals['_FORECASTRESPONSE_COMPONENTSENTRY']._serialized_end=860
  _globals['_DEFAULTPARAMETERSRESPONSE']._serialized_start=862
  _globals['_DEFAULTPARAMETERSRESPONSE']._serialized_end=903
  _globals['_FORECASTSERVICE']._serialized_start=906
  _globals['_FORECASTSERVICE']._serialized_end=1074
# @@protoc_insertion_point(module_scope)
