# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: prophet.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'prophet.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rprophet.proto\"4\n\x0f\x46orecastRequest\x12\x10\n\x08\x63sv_data\x18\x01 \x01(\x0c\x12\x0f\n\x07periods\x18\x02 \x01(\x05\"E\n\x10\x46orecastResponse\x12\x16\n\x0c\x66orecast_csv\x18\x01 \x01(\x0cH\x00\x12\x0f\n\x05\x65rror\x18\x02 \x01(\tH\x00\x42\x08\n\x06result2D\n\x0fProphetForecast\x12\x31\n\x08\x46orecast\x12\x10.ForecastRequest\x1a\x11.ForecastResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'prophet_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FORECASTREQUEST']._serialized_start=17
  _globals['_FORECASTREQUEST']._serialized_end=69
  _globals['_FORECASTRESPONSE']._serialized_start=71
  _globals['_FORECASTRESPONSE']._serialized_end=140
  _globals['_PROPHETFORECAST']._serialized_start=142
  _globals['_PROPHETFORECAST']._serialized_end=210
# @@protoc_insertion_point(module_scope)
